<h1>Meetup</h1>

<ul>


    <div class="container">
            <table class="table table-striped table-bordered table-hover">
                    <thead>
                            <th class="text-center">Nom du Meetup</th>
                            <th class="text-center">Description</th>
                            <th class="text-center">Date de début</th>
                            <th class="text-center">Date de Fin</th>
                            <th class="text-center">Modifier</th>
                            <th class="text-center">Suprimer</th>
                    </thead>
                    <tbody>
                            <?php foreach ($this->meetup as $meetup): /* @var $meetup \Application\Entity\Film */ ?>
                                    <td class="text-center"><?= $meetup->getTitle() ?></td>
                                    <td class="text-center"><?= $meetup->getDescription() ?></td>
                                    <td class="text-center"><?= $meetup->getDateStart() ?></td>
                                    <td class="text-center"><?= $meetup->getDateEnd() ?></td>
                                    <td class="text-center"><a href="meetup/update/<?= $meetup->getID(); ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                                    <td class="text-center"><a href="meetup/delete/<?= $meetup->getID(); ?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                            <?php endforeach; ?>
                    </tbody>
            </table>
    </div>

</ul>

<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new</a>
